### ISSUE TITLE
Build multiple images

### ISSUE THREAD

**Issue by rclark** [mapbox/ecs-conex#10] opened 2016-05-15 22:04 UTC
On AWS, a "task" can run one or more docker images. I can definitely imagine reasons why a Github repository might contain multiple dockerfiles to build more than one image. It would be worth considering how this scenario would be handled by this repo.

**Comment by vsmart** [comment] 2018-08-13 09:32
Closing, duplicate of #121.

**Closed by vsmart** 2018-08-13 09:32 UTC
Labels: enhancement
